# Generated by Django 4.0.5 on 2022-07-15 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='creator_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
