# Generated by Django 4.0.5 on 2022-07-15 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_description_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
