# Generated by Django 4.0.5 on 2022-07-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watching',
        ),
    ]
