# Generated by Django 4.0.5 on 2022-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_auction_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
