# Generated by Django 4.0.5 on 2022-07-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=0),
        ),
    ]
