# Generated by Django 4.0.5 on 2022-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='error',
            field=models.CharField(default='Sorry, you must enter a valid amount over the starting bid or current bid.', max_length=1000),
        ),
    ]
